### ISSUE TITLE
Feature Request: Yarn/NPM Package for The Algorithms

### ISSUE THREAD

**Issue by Exortions** [TheAlgorithms/JavaScript#1025]
This would be a node module that contains all of the algorithms in the repository. Things like this could also be implemented in Python, etc.

There could be a script running in the cloud that checks for new commits, and then updates the package with the new algorithms/changes.

**Comment by raklaptudirm** [comment]
The algorithms implemented in this repository are not supposed to be used in production environments. As highlighted in the readme, they are only supposed to be used for educational purposes. There are many packages in npm that are more suited for specific applications, provide API stability guarantees, and have better code focused on performance and stability than readability. So in my opinion, publishing this repository as a package goes against what this repository is about.
