### ISSUE TITLE
SecondLargestElement Algorithm returns wrong value

### ISSUE THREAD

**Issue by Ankush263** [TheAlgorithms/JavaScript#1035]
for the array [-1, -2, -3, -4] it returns 0

**Comment by appgurueu** [comment]
I assume the algorithm just wasn't intended to support negative values as it uses `0` as a default min value.

**Comment by Ankush263** [comment]
Should I make a PR

**Comment by appgurueu** [comment]
> Should I make a PR

I've already fixed it, see the linked PR.
