### ISSUE TITLE
Fibonacci Matrix doesn't use `BigInt`s

### ISSUE THREAD

**Issue by Rudxain** [TheAlgorithms/JavaScript#1047]
[This file](https://github.com/TheAlgorithms/JavaScript/blob/master/Maths/Fibonacci.js) uses `Number`s at the matrix algorithm to compute the nth number in the Fibonacci sequence. My reasons to recommend `BigInt` are these:
* `BigInt`s can't use *Binet's Formula*, nor the [rounded and simpler variant](https://en.wikipedia.org/wiki/Fibonacci_number#Computation_by_rounding) because that requires arbitrary-precision floating-point computation
* The repeated-addition algo is more suitable for generator functions, but the matrix algo is used to get as fast as possible to the nth term in the sequence, regardless of the exponent value, without sequentially "touching" every term in the sequence
* Exponentiation (matrix or not) usually yields **huge** numbers, `BigInt`s are more suitable for this task. Using `Number`s would usually return `Infinity`
* All numbers used are integers, no need for floating-point or fixed-point

I want to make a PR, but I opened this issue to wait for approval

**Comment by appgurueu** [comment]
I approve this. Go ahead and open your PR.
