### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by AmitKushwah916** [TheAlgorithms/JavaScript#1059]

**Comment by raklaptudirm** [comment]
@appgurueu Could you delete this issue. I am not at my pc rn.

**Comment by appgurueu** [comment]
I see no option to delete the issue under "notifications". Perhaps only the repo owner can the delete the issue?

**Comment by raklaptudirm** [comment]
It should show in the issue page on the right hand column.

**Comment by appgurueu** [comment]
![Bildschirmfoto von 2022-07-25 13-25-13](https://user-images.githubusercontent.com/34514239/180767044-9aed65ee-4070-4cf4-8f5b-fab57b1c5e1b.png)
