### ISSUE TITLE
calcFactorial(n) in Factorial.js must return integer value instead of a string value

### ISSUE THREAD

**Issue by itsAkshayDubey** [TheAlgorithms/JavaScript#1092]
Hi,

As I can see, the [current implementation](https://github.com/TheAlgorithms/JavaScript/blob/master/Maths/Factorial.js) of calculating the factorial of a number returns a string like "The factorial of 5 is 120" instead this function must return an integer value of 120, so that we can use this function in other algorithms to calculate factorial without having to write logic to calculate factorial and thereby increasing code redundancy in this repo. Currently, I working on an algorithm that requires me to calculate the factorial of a number but I am unable to use calcFactorial(n) from Factorial.js as it returns a string.  

Regards,
Akshay

**Comment by appgurueu** [comment]
Agreed. Feel free to fix it.
