### ISSUE TITLE
Improper and incomplete implementation of CycleDetection.js

### ISSUE THREAD

**Issue by 10kartik** [TheAlgorithms/JavaScript#1097]
Implementation of [CycleDetection.js](https://github.com/TheAlgorithms/JavaScript/blob/master/Data-Structures/Linked-List/CycleDetection.js) seems inappropriate.

- Weird function name `main()` and its invocation can cause the program to crash.
- Tests are missing.
- Not exported, Hence not resuable.
- Can be optimized further (Optional)

**Comment by appgurueu** [comment]
The algorithm is complete. It has poor code quality though, as you have pointed out. Feel free to fix it.
