### ISSUE TITLE
DateToDay.js giving wrong day

### ISSUE THREAD

**Issue by chrisjwaddell** [TheAlgorithms/JavaScript#1121]
DateToDay("1/1/2020") returns "Friday" but its "Wednesday". Other basic tests show the wrong day as well.

**Comment by alpesh-rama** [comment]
Please assign me to this issue. Thank you

**Comment by rajprogrammerbd** [comment]
I want to work on please, Thank you.

**Comment by anshul137** [comment]
I would like to solve this problem.
thanks

**Comment by raji2004** [comment]
please assign it to me

**Comment by chrisgalvan** [comment]
I have also submitted a solution to current bug

**Comment by Hanee-Solanki** [comment]
Hi, this is my first time contributing to an open-source project. I wanted to know if we have to use the same algorithm to calculate the day or if we could use a different one. Please advise.

**Comment by raklaptudirm** [comment]
There are already several pull requests fixing this issue. I will advise people to not take this issue up any more.

**Comment by Gauri-AB** [comment]
Hii Sir, pls assign this issue to me.

**Comment by appgurueu** [comment]
> Hii Sir, pls assign this issue to me.

We already have two working fixes for this issue.
