### ISSUE TITLE
file name palindrome.test.js should be Palindrome.test.js to follow UpperCamelCase

### ISSUE THREAD

**Issue by AbdulAhadKhan0308** [TheAlgorithms/JavaScript#1143]
file is at Recursive/test/palindrome.test.js

**Comment by appgurueu** [comment]
Makes me question or contribution guideline. Usually file name conventions dictate lower snake case; `UpperCamelCase` is reserved for classes. Files exporting single functions should probably not be using `UpperCamelCase` but rather `lowerCamelCase` (like the funcs) or `lower_snake_case`.

**Comment by raklaptudirm** [comment]
This repository uses UpperCamelCase for all JavaScript files.
