### ISSUE TITLE
Validate Url Issues

### ISSUE THREAD

**Issue by meirroth** [TheAlgorithms/JavaScript#1183]
Two issues found with the Validate Url algorithm:

1. A string is considered to be valid URL if it starts with www. even though it does not have https

- `validateUrl('www.google.com')` // returns true
- `validateUrl('google.com')` // returns false

2. A valid URL returns false if starts with www like:
- `validateUrl('https://wwwdomain.com')` // returns false

**Comment by SubhamB2003** [comment]
Can i try this

**Comment by SubhamB2003** [comment]
> Two issues found with the Validate Url algorithm:
> 
> 1. A string is considered to be valid URL if it starts with [www](http://www). even though it does not have https
> 
> * `validateEmail('www.google.com')` // returns true
> * `validateEmail('google.com')` // returns false
> 
> 2. A valid URL returns false if starts with www like:
> 
> * `validateEmail('https://wwwdomain.com')` // returns false

**Comment by appgurueu** [comment]
> Can i try this

No (see the current PR).

**Comment by 609harsh** [comment]
is it still open?

**Comment by appgurueu** [comment]
Yesn't? The solution might be a removal of the "algorithm" though.

**Comment by trasherdk** [comment]
Hmm. None of those test cases are valid email addresses.

`validateEmail('www.google.com')` // returns true :question:

**Comment by meirroth** [comment]
@trasherdk Oops... It's a typo. Should say `validateUrl('www.google.com')`.
Fixed now.

**Comment by Aditya-Naresh** [comment]
Is this issue still open?

**Comment by appgurueu** [comment]
> Is this issue still open?

Yes, but bear in mind that validating URLs is much more complex than presented here:

![URL syntax diagram](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/URI_syntax_diagram.svg/1068px-URI_syntax_diagram.svg.png)

(from https://en.wikipedia.org/wiki/URL)

**Comment by 0-harshit-0** [comment]
hello, I would like to work on this.
