### ISSUE TITLE
adding Contributing guidelines 

### ISSUE THREAD

**Issue by itsvinayak** [TheAlgorithms/Javascript#120]
contributing guidelines are needed to clear doubts of new contributor

**Comment by itsvinayak** [comment]
@cclauss  please look into this issue

**Comment by itsvinayak** [comment]
@cclauss please have a look to this [PR](https://github.com/TheAlgorithms/Javascript/pull/136) 
it's almost same as TheAlgorithms/Python one

**Comment by cclauss** [comment]
I will send you some suggestions tomorrow.

**Comment by itsvinayak** [comment]
thanks





Vinayak sharma

9259888898

IERT allahabad
CSE 3rd year

**Comment by itsvinayak** [comment]
@cclauss should I close this issue
