### ISSUE TITLE
Want To Add Many Algorithms For Trees in JavaScript

### ISSUE THREAD

**Issue by Harshal-Jadhav** [TheAlgorithms/JavaScript#1244]
Following Are the Algorithms for Trees I would like to Add in this Repository.

- Level Order Traversal.
- Zig-Zag Traversal.
- Left or Right View.
- Similar Tree Check.
- Mirror Tree Check.

I would be glad if allowed to Help.

**Comment by appgurueu** [comment]
Yes, of course you may add all these algorithms. Try to stick them all in a generic `Tree` class (unless you want to limit them to binary trees).

Please don't open issues to request algorithms / announce that you are working on algorithms though. Just work on it right away and open PRs.

**Comment by Harshal-Jadhav** [comment]
Got it working on them
