### ISSUE TITLE
[OTHER]: It is not looks good for create a separate section for connect with us section.

### ISSUE THREAD

**Issue by gkm0001** [TheAlgorithms/JavaScript#1356]
### What would you like to share?

It is not looks good , I can improve it ,please assign me.

<img width="957" alt="Screenshot 2023-09-07 080821" src="https://github.com/TheAlgorithms/JavaScript/assets/121250607/f3a86433-4904-4c2e-a32f-18e5ff1edc28">

**Comment by appgurueu** [comment]
That should be an issue on the website repo.
