### ISSUE TITLE
[FEATURE]: Add more algorithms

### ISSUE THREAD

**Issue by prasad-chavan1** [TheAlgorithms/JavaScript#1371]
## Add more algorithms
- This will enhance system.
- People will able to get all resources at one platform.

### Examples

BitonicSort, Hashes, Cryptography, Tress, Graphs, etc...

**Comment by prasad-chavan1** [comment]
@appgurueu  I'll work on this too..

**Comment by appgurueu** [comment]
Please don't open such broad issues for adding algorithms. You may open a specific issue if you're looking for guidance related to how/whether to implement a particular algorithm.
