### ISSUE TITLE
[FEATURE]: Last Element

### ISSUE THREAD

**Issue by abrehan2** [TheAlgorithms/JavaScript#1373]
### Motivation

I will add a code written in js that is used to find a last element in the array. 
Folder: Bit Manipulation

**Comment by appgurueu** [comment]
What does this have to do with bit manipulation?

**Comment by Kireet7852** [comment]
This code should be added in '/Data-Structures
/Array/'.

**Comment by abrehan2** [comment]
Sorry. In the arrays.

**Comment by rko0211** [comment]
Hello sir i would like to contribute on this issue please assign me this issue. Thank You..

**Comment by 0xprathamesh** [comment]
Can you assign me the task i knew the solution very well. Thank You!

**Comment by appgurueu** [comment]
Just returning the last element of an array is a trivial programming problem and hardly of algorithmic value; it doesn't warrant inclusion.
