### ISSUE TITLE
[FEATURE]: Height of tree

### ISSUE THREAD

**Issue by vishal-sharma-369** [TheAlgorithms/JavaScript#1375]
### Motivation

I want to add a code for finding the height of a tree in the tree algorithms

**Comment by Karamraj** [comment]
Can I take this?

**Comment by aarti-1108** [comment]
![Screenshot (142)](https://github.com/TheAlgorithms/JavaScript/assets/97671310/b9351c03-9cea-4790-91c8-3e7a74d14d50)

It is already present in the bfs file under trees. Do we have to move it in a separate file?

**Comment by vishal-sharma-369** [comment]
@aarti-1108 In that case we don't need to move this in separate file if it is already present.
