### ISSUE TITLE
[Question]: How can i work on multiple file? do i have to wait for first pr to be merged?

### ISSUE THREAD

**Issue by developerr-ayush** [TheAlgorithms/JavaScript#1387]
### What would you like to share?

 i want to work on multiple files like recently i had enhance a code of a function and also created a new feature so can I upload it on one pr or wait for first pr to be get merged?

**Comment by appgurueu** [comment]
You should make all your related changes in one PR. Just search for how to make a PR, there's e.g. this [guide for beginners](https://opensource.com/article/19/7/create-pull-request-github).
