### ISSUE TITLE
[FEATURE]: Length Conversion

### ISSUE THREAD

**Issue by 0APOCALYPSE0** [TheAlgorithms/JavaScript#1391]
### Motivation

I think we should have a Length Conversion algo.

### Examples

This feature can be used to convert the measures of length from one unit to another

### Additional information

I already raised a PR for this Feature. Please review and approve. If there is any please let me know. I'll fix it.
Thanks

**Comment by appgurueu** [comment]
It's unnecessary to open an issue if you've already opened a PR.
