### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by amanr-dev** [TheAlgorithms/JavaScript#1396]
### Motivation

Add a scroll-up button on the home page.

### Examples

Scroll up button

### Additional information

Add a scroll-up button on the home page.

**Comment by rezaaar** [comment]
Hi, can i know where to put the scroll-up button? is that on the directory.MD? Thankyou

**Comment by raklaptudirm** [comment]
No scroll-up buttons are necessary in this repo afaik. Feel free to elaborate to reopen this issue.
