### ISSUE TITLE
Add more algorithms

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/Javascript#14]
Please add more algorithms to this repo. 

See the structure and README of this repo for reference
https://github.com/TheAlgorithms/Python

**Comment by meetzaveri** [comment]
#18

**Comment by kulshreshtha19** [comment]
[bubblesort.js.txt](https://github.com/TheAlgorithms/Javascript/files/1821995/bubblesort.js.txt)
Uploading bubblesort algorithm in javascript. kindly merge it.
Thank you

**Comment by ntedgi** [comment]
#84

**Comment by raviolliii** [comment]
#83 Added SHA-1 and SHA-256 Hashing algorithms

**Comment by Satzyakiz** [comment]
I would like to work on this issue.

**Comment by itsvinayak** [comment]
#195

**Comment by TangibleDream** [comment]
I added GridGetX and GridGetY #222

**Comment by harshitagrawal7733** [comment]
What to do? 
Add more alogorithms is the goal?

**Comment by itsvinayak** [comment]
@harshitagrawal7733 adding algorithms which follow coding standards of repo 
please have a look [here](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md)

**Comment by dev348** [comment]
Yeah sure 👍🏾

**Comment by aakhtar3** [comment]
I just added a few algorithms.

Are we able to add diagrams? I have a bunch of notes that tie to my code to help understand the data structures and algorithms.

**Comment by vinay72** [comment]
@AnupKumarPanwar Hi, Anup. I've added a De-facto unbiased shuffle algorithm also known as the Fisher-Yates shuffle algorithm, so please review and merge my PR.

**Comment by arjun1311** [comment]
Hi, I have added an algorithm please review and merge my PR

**Comment by allenjamesvinoy14** [comment]
Can you please open an issue with hacktoberfest label to add data structures as well? Or may I add a data structure under this issue?

**Comment by sonechca** [comment]
Hi, I added a new algorithm "Tree Sort".
Can you check my code?
Thank you https://github.com/TheAlgorithms/Javascript/pull/513

**Comment by elouie-code** [comment]
Added a linked list reverse order algorithm. can you review please? [#528](https://github.com/TheAlgorithms/Javascript/pull/528)

Thanks!

**Comment by achudinovskyh** [comment]
Hi, I've added new Search algorithm, can you check it please? Thank you! #542
