### ISSUE TITLE
[FEATURE]: Add a palindrome validating code in the "string" folder under Hacktoberfest

### ISSUE THREAD

**Issue by abrehan2** [TheAlgorithms/JavaScript#1451]
### Motivation

Hey,

I am eager to mark my first contribution by merging my solution into your repository. Thanks.

**Comment by jatin-2708** [comment]
Hey, 
please assign this issue to me.
I am very eager to work on this issue

**Comment by abrehan2** [comment]
Sorry, I'll be working on this issue. Find an another issue. Thanks.

**Comment by raklaptudirm** [comment]
Don't open issues for missing algorithms.
