### ISSUE TITLE
[OTHER]: Add gidpod ready to code badge in README.md

### ISSUE THREAD

**Issue by rohitkbc** [TheAlgorithms/JavaScript#1465]
#### Description
</br>
Project is ready to run in gitpod. It has gitpod.yml file also.
    
Just need to add **Gitpod ready to code** badge on main README.md file
![image](https://github.com/TheAlgorithms/JavaScript/assets/100275369/b5ce00c0-7b79-40c8-8814-2c0d0a73ae5a)
I can work on this issue.
I am participating in **hacktoberfest**.
Can you assign it me?

**Comment by appgurueu** [comment]
There's no need for this issue. Discussion can happen in the PR.
