### ISSUE TITLE
Backtracking

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [TheAlgorithms/JavaScript#1497]
I want to add  some more Backtracking Algorithms Like --

1) warnsdorff's algo
2) find all distinct subsets of a given set
3) find paths from corner cell to middle cell in maze
4) longest possible Route in matrix with hurdles
5) Hamiltonian cycle
6) sudoko puzzle solver
7) printing all possible permutations
8) find all subsets
9) Tug of war
10) power set Lexicographically
11) word break
12) Knights tour
13) N QUEUE
14) Rat in maze
15) Subset sum
16) Remove Invalid Parenthesis

Can you please assign this, I am interested to contribute myself in hacktoberfest_23 : )

**Comment by appgurueu** [comment]
Sorry, but we won't assign you 16 backtracking algorithms. Just check that we don't already have them, and open PRs adhering to our contribution guidelines (with a proper implementation, JSDoc comment(s), and tests).
