### ISSUE TITLE
more contributors are needed

### ISSUE THREAD

**Issue by itsvinayak** [TheAlgorithms/Javascript#155]
- [ ]  Adding hints and doctest to old codes
- [ ] Reviewing  Pending PRs ( fixing code format by running `npm standard --fix` PR labeled under "failing npm standards"  ) 
- [ ] Helping new Contributors 
- [ ] Add more algorithms 

thank you

**Comment by DAMMAK** [comment]
I'm ready to contribute... but don't know what to fix, contribute or do...

**Comment by itsvinayak** [comment]
@DAMMAK you can do many things:
code review
adding algorithms
or just fix something

**Comment by itsvinayak** [comment]
@DAMMAK  start by reading [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md)

**Comment by DAMMAK** [comment]
okay thanks... I will do that..

**Comment by priyanshk20** [comment]
i want to contribute too

**Comment by itsvinayak** [comment]
That would be great, @priyanshk20 
thanks

**Comment by Aditya-Ramachandran** [comment]
Okay, I am ready to contribute too...
But what do I have to do exactly??

**Comment by itsvinayak** [comment]
@Aditya-Ramachandran  you can do anything, this repo is a learning place just read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md)

you can -
- [ ]  Adding hints and doctest to old codes
- [ ] Reviewing  Pending PRs
- [ ] Helping new Contributors
- [ ] Add more algorithms

thank you
@itsvinayak

**Comment by Aditya-Ramachandran** [comment]
Oh okay, thank you so much @itsvinayak

**Comment by s-ndipchaudh-ri** [comment]
hey team, 
I am interested to contribute in project.

**Comment by Maxz2136** [comment]
Hello, I want to contribute to this project
I am little new to JS, can anybody tell me how to add doctest to old code?

**Comment by remmaso** [comment]
Ready to contribute asap

**Comment by itsvinayak** [comment]
> Ready to contribute asap

hey, @remmaso  welcome to  community

**Comment by itsvinayak** [comment]
> Hello, I want to contribute to this project
> I am little new to JS, can anybody tell me how to add doctest to old code?

hey @Maxz2136  please have a [look here](https://www.npmjs.com/package/doctest)
and also look in this issue #142

**Comment by JimmyJoo** [comment]
Hi I wanna contribute to this project

**Comment by itsvinayak** [comment]
@JimmyJoo  sure, go on

**Comment by abxsantos** [comment]
Hi! I want to contribute too. Adding tests to the existing code is a possibility? Or is it better to review some PR requests?

**Comment by itsvinayak** [comment]
Hey, @abxsantos that will be great, it's all your wish you can add test or review PR

**Comment by abxsantos** [comment]
> Hey, @abxsantos that will be great, it's all your wish you can add test or review PR

Great! I'll start by adding some unit tests with jest for the existing algorithms. Then I'll move to review PR.

**Comment by komputarist** [comment]
Hi. I already made some contributions. Here is a [PR](https://github.com/TheAlgorithms/Javascript/pull/348)

**Comment by thoughtlessmind** [comment]
Hey! I really liked this repo. I'm wondering why I couldn't find it earlier😅. I'm hoping to contribute here as much as possible.
