### ISSUE TITLE
[FEATURE]: Data structure, Disjoint Set

### ISSUE THREAD

**Issue by its-kunal** [TheAlgorithms/JavaScript#1583]
### Motivation

There is also a data structure to solve specific problems related to graphs—overlapping graphs and also used in algorithms like the Kruskal algorithm.

**Comment by appgurueu** [comment]
We already have such a "union find" data structure (placed in the "search" folder), and our implementation of Kruskal's algorithm brings its own. How to refactor these may be discussed, but the feature is already there.
