### ISSUE TITLE
Build DIRECTORY.md with JavaScript, not Python

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Javascript#160]
We present all of of our algorithms in an organized list, [__DIRECTORY.md__](../blob/master/DIRECTORY.md) so visitors can rapidly find topics of interest.  Currently DIRECTORY.md is being autogenerated by one of [our GitHub Actions](../tree/master/.github/workflows) which [uses Python code](../blob/master/.github/workflows/update_directory_md.yml#L11-L57) to create the directory text.

Why should the JavaScript repo rely on Python code?!?  Especially given that GitHub Actions fully support the [creation of JavaScript-based Actions](https://help.github.com/en/actions/building-actions/creating-a-javascript-action).  Can we use JavaScript to autogenerate DIRECTORY.md and lose the Python code in the process?

**Comment by sahilbansal17** [comment]
@cclauss I would like to work on this.

**Comment by cclauss** [comment]
No need to wait for permission... Just do it!

**Comment by sahilbansal17** [comment]
I have added the workflow as a js file in PR #163 .
The yml file needs to be updated so that the action can be run, I tried to look up github actions on javascript documentation and try to figure it out but didn't understand how to run the standalone js file. Some help will be appreciated.
