### ISSUE TITLE
Rationalize the two different implementations of heap sort

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Javascript#164]
We have [two different implementations of heap sort](https://github.com/TheAlgorithms/Javascript/tree/master/Sorts).  Can we build a benchmark to prove which one is faster or better than the other?  Benchmark against small datasets, large datasets, and empty datasets.  It is OK to keep both if they have different strengths and weaknesses.  If there is a clear winner, let's delete the other one.

**Comment by sahilbansal17** [comment]
@cclauss It seems that both the implementations are exactly the same algorithmically.

**Comment by cclauss** [comment]
> Can we build a benchmark to prove which one is faster or better than the other?

It would be cool to have a benchmark because then we would have ___proof___ that they are the same and have the same performance for multiple datasets.  Hint: I doubt it.

Such a benchmark could be extended to do side-by-side performance tests of all 19 of our sort algorithms.  Benchmarks are cool and they have the power to push our contributors to optimize.

**Comment by poyea** [comment]
Also, there's something more we can do. At least [BogoSort](https://github.com/TheAlgorithms/Javascript/blob/master/Sorts/BogoSort.js#L7) has an `isSorted` function and a `shuffle` function. We can make use of these two functions to build our test sets for the whole `sort/`.

**Comment by cclauss** [comment]
;-)  Are lines 10-13 needed?

**Comment by poyea** [comment]
> ;-) Are lines 10-13 needed?

If the loop starts with `i=1` and compares `this[i-1]` with `this[i]` then it is, but no for the current code.

**Comment by cclauss** [comment]
Does the loop ever execute at all?

**Comment by poyea** [comment]
Yes. It's kind of an extension for the Array object. That's why we can use it directly.
https://js.do/code/438412

**Comment by cclauss** [comment]
Our test cases are when `length < 2` so...
document.write([].isSorted());  // --> true
document.write([1].isSorted());  // --> true

Now comment out lines 10-13 and run again.

You will get the exact same results because the loop never runs.

Lines 10-13 can be deleted.
