### ISSUE TITLE
[FEATURE]: The styling of the boxes can be better.

### ISSUE THREAD

**Issue by ayushrskiaa** [TheAlgorithms/JavaScript#1693]
### Motivation

![image](https://github.com/user-attachments/assets/3bf2cba7-1ec7-4d5a-a891-bd73e9b0a74b)
 

the styling of the boxes can be more attractive. I can do this please assign me this.

**Comment by sagarbendale2004** [comment]
"Help Wanted" - Where do i find this boxes??  In which file the code is written for this boxes...

**Comment by aryansoni13** [comment]
Interested in contributing to this assign me the task

**Comment by abhishekkrjha2811** [comment]
i can do this assign me this work

**Comment by appgurueu** [comment]
This issue does not belong here. You could file this on https://github.com/TheAlgorithms/Website. But there's a high chance it will be rejected; I assume the boxes are just standard Material theme and I don't see why the website maintainers would want to diverge from that.
