### ISSUE TITLE
Re-orgainze files and folders in the repository

### ISSUE THREAD

**Issue by poyea** [TheAlgorithms/Javascript#170]
We have to re-organize some files and folders in this repository, as per discussion [here](https://github.com/TheAlgorithms/Javascript/pull/167#issuecomment-627237727). These actions include:

- [x] [Remove our Algorithms folder and put the contents in their correct category](https://github.com/TheAlgorithms/Javascript/tree/master/Algorithms)
- [x] [Rename Linear-Algebra-Javascript to Linear-Algebra](https://github.com/TheAlgorithms/Javascript/tree/master/Linear-Algebra-Javascript)
- [x] QuickSelect.js should go to arrays or something else
- [x] Conversions, Ciphers, Hashes, should they be in the maths directory?

Feel free to add your suggestions.

**Comment by cclauss** [comment]
I believe that Conversions, Ciphers, and Hashes are classes of algorithms that are more useful separated in their own directories rather then lumping them all in the maths directory.  The idea is to help visitors to find related things quickly and lumping them all together would not help in that regard.

**Comment by cclauss** [comment]
Arrays are a data type.  Searches are algorithms.

**Comment by itsvinayak** [comment]
#172

**Comment by Altesse2** [comment]
> Arrays are a data type.  Searches are algorithms.

👍👍👍
