### ISSUE TITLE
[FEATURE]:  Dynamic Link  for Problem Code Viewing and 

### ISSUE THREAD

**Issue by PRAteek-singHWY** [TheAlgorithms/JavaScript#1702]
### Motivation

Implement a feature that dynamically converts the name of a problem into a clickable link when hovered over. Upon clicking, the user will be directed to a page displaying the code solution for that specific problem.

### Examples

When hovering over the name of a particular problem in the problem list, the name should be styled as a link (with hover effects).
The link will redirect users to a dedicated page or modal where the code solution for the corresponding problem is displayed.

The feature should ensure a seamless transition from problem name to code display, improving the user experience by offering quick access to solutions.

**Comment by samyak-aditya** [comment]
hey can you assign it to me

**Comment by Vishrut99** [comment]
I can do that Easiy so can you assigned me the work

**Comment by appgurueu** [comment]
Irrelevant for this repo. You might want to file this somewhere else.
