### ISSUE TITLE
[FEATURE]: When a user search for something we can show how many no of results are matched

### ISSUE THREAD

**Issue by dhruvishah122** [TheAlgorithms/JavaScript#1718]
### Motivation

Enhancing searchbar

**Comment by SukhvirKooner** [comment]
Hi, I'd love to work on this feature and contribute to the project! Could you please assign me to this issue under Hacktoberfest? I'm excited to help implement the result count functionality. Thank you!

**Comment by appgurueu** [comment]
Unrelated to this repo. You might want to file this under https://github.com/TheAlgorithms/Website.
