### ISSUE TITLE
[FEATURE]: Want to add Word Break problem in Backtracking

### ISSUE THREAD

**Issue by amrit1004** [TheAlgorithms/JavaScript#1736]
### Motivation

When adding the Word Break problem to the backtracking section of the project, the motivation behind this feature is to enhance the problem-solving repertoire by incorporating a popular and frequently encountered interview question that blends both dynamic programming and backtracking concepts. The Word Break problem challenges a user's ability to explore multiple possibilities recursively while making optimal subproblem choices, which is a core application of backtracking.

Motivation:
Strengthens Backtracking Concepts: The problem showcases how backtracking can be used effectively to break down a complex problem into smaller parts, making it a perfect fit for this section.
Interview Preparation: Word Break is a classic problem asked in coding interviews by companies like Google, Facebook, and Amazon, making it a valuable addition for developers looking to practice and refine their skills for real-world technical assessments.
Blends Dynamic Programming and Backtracking: The problem introduces a way to solve it both via backtracking and dynamic programming, helping learners understand when and how backtracking can be optimized.
Real-World Use Cases: Word segmentation is a practical problem in fields like Natural Language Processing (NLP) and text prediction. Including it provides learners with an opportunity to see how backtracking applies to real-world problems.

**Comment by appgurueu** [comment]
Please don't dump LLM spam on us.
