### ISSUE TITLE
insert or adding the algorithm of Backtracking:  Hamiltonian Cycle:

### ISSUE THREAD

**Issue by Atuloli01** [TheAlgorithms/JavaScript#1756]
### Motivation

other can know the algorithm and get the access easily from this website

### Examples

Backtracking:  Hamiltonian Cycle: Find a cycle that visits each vertex in a graph exactly once and returns to the starting vertex.

### Possible workarounds

adding Algorithm

### Additional information

adding the algorithm into your website to help others
#assignAlgorithm
/assign

**Comment by gourab9817** [comment]
I would to love to solve this issue , could you please assign it to me.

**Comment by appgurueu** [comment]
Essentially a duplicate of #1735; the difference between hamiltonian cycle and path isn't very significant.
