### ISSUE TITLE
Addition of Web Programming

### ISSUE THREAD

**Issue by ruppysuppy** [TheAlgorithms/Javascript#187]
Can I work on addition of the web programming segment as available in [TheAlgorithms/Python](https://github.com/TheAlgorithms/Python/tree/master/web_programming)? I would like to work on the [Open Weather Maps](https://github.com/TheAlgorithms/Python/blob/master/web_programming/current_weather.py) example.

**Comment by itsvinayak** [comment]
@ruppysuppy go on,
let us know if you need any help by [issues](https://github.com/TheAlgorithms/Javascript/issues/new/choose) or on [gitter](https://gitter.im/TheAlgorithms/community)
