### ISSUE TITLE
TimingFunction/IntervalTimer with NodeJS

### ISSUE THREAD

**Issue by nandanvasudevan** [TheAlgorithms/Javascript#239]
The function **works fine on the browser**. The instance returns the time run.
However, **nodeJS uses a completely different structure** for it's timers.
It *may not be necessary in NodeJS*. I genuinely think it helps otherwise, I use it to time my unit tests.

The value returned by setInterval() is the total runtime of the timer.

**Comment by itsvinayak** [comment]
@nandanvasudevan is there any program in the repo with this issue, please list here

**Comment by InerkyJad** [comment]
Hi @nandanvasudevan, i can see that your request doesn't really involve any algorithm, or issues in the repository.
Still You can use `console.time()` to start a timer and use `console.timeEnd()` to stop it, this is available on both NodeJs and in the standard JavaScript and it can be used to calculate the run time.
