### ISSUE TITLE
Adding more algorithm in String [ Valid Palindrome ]

### ISSUE THREAD

**Issue by nil1729** [TheAlgorithms/Javascript#289]
Remove at most a character in a string so that String becomes palindrome or not.
Can I contribute to this solution?

**Comment by patelvimal** [comment]
Example string "xyabyx" if I remove b from the string it will become a palindrome. Is it like this?

**Comment by nil1729** [comment]
Yes. Can I do this?

**Comment by itsvinayak** [comment]
hey @nil1729 go for it,
