### ISSUE TITLE
Quick Sort in Sorting Algorithm

### ISSUE THREAD

**Issue by aniketsingh98571** [TheAlgorithms/Javascript#313]
Quick Sort Algorithm using Javascript.
@itsvinayak @cclauss  Please assign me this issue.

**Comment by aniketsingh98571** [comment]
@itsvinayak @cclauss Please assign me this issue.

**Comment by cclauss** [comment]
Please do not wait for permission.  We do not assign issues.  We review pull requests.  If you see something that needs fixing then submit a pull request.  If two contributors submit pull requests to fix the same issue, it is almost always a learning experience.
