### ISSUE TITLE
Adding documentation for doctest to help new contributors

### ISSUE THREAD

**Issue by itsvinayak** [TheAlgorithms/Javascript#461]
[doctest help](https://www.npmjs.com/package/doctest)

**Comment by Bhairavi-shah** [comment]
Hey! I would like to work on this. Currently which all programs need doctest? Is there something I can refer?

**Comment by itsvinayak** [comment]
sure  @Bhairavi-shah 
some files have [doctest](https://www.npmjs.com/package/doctest)
refer to #142

**Comment by jayantchaudhary002** [comment]
I would like to work on this
