### ISSUE TITLE
improving code quality

### ISSUE THREAD

**Issue by itsvinayak** [TheAlgorithms/Javascript#469]
improving the code quality of the repo,
https://lgtm.com/projects/g/TheAlgorithms/Javascript/alerts/?mode=list

**Comment by elouie-code** [comment]
@itsvinayak looking at this, mind if I take it?

**Comment by jayantchaudhary002** [comment]
I would like to work on this

**Comment by itsvinayak** [comment]
sure @jayantchaudhary002 go for it !!

**Comment by itsvinayak** [comment]
sure @elouie-code go for it, and please refer to the files you are working on!!
