### ISSUE TITLE
Implemntation of AVL Tree in JavaScript

### ISSUE THREAD

**Issue by Lakhan-Nad** [TheAlgorithms/Javascript#535]
__AVL tree__ is a self balancing tree. 
All the operations i.e. search, insertion, deletion take O(logN) time.
Read more about AVL Tree [here](https://en.wikipedia.org/wiki/AVL_tree)

**Comment by itsvinayak** [comment]
hey @Lakhan-Nad, please send a PR

**Comment by Lakhan-Nad** [comment]
@itsvinayak  I already sent one #536 
If there are any changes or updates please let me know.
Thank You
