### ISSUE TITLE
Tests failing: Files need to be fixed or removed

### ISSUE THREAD

**Issue by cclauss** [TheAlgorithms/Javascript#539]
See GItHub Actions output of #538
* [ ] Dynamic-Programming/MinimumCostPath.js
* [ ]  Linear-Algebra/test/test.js
* [ ]  String/LevenshteinDistance.test.js

**Comment by DhruvGheewala** [comment]
For `Dynamic-Programming/MinimumCostPath.js`, can you provide the test cases on which code fails !!

**Comment by raklaptudirm** [comment]
@cclauss 
- [x]  Dynamic-Programming/MinimumCostPath.js
- [x] Linear-Algebra/test/test.js
- [x] String/LevenshteinDistance.test.js

See #609
