### ISSUE TITLE
add extra comments for better understanding of algorithms.

### ISSUE THREAD

**Issue by anukulSaini** [TheAlgorithms/Javascript#564]

**Comment by marsonya** [comment]
hi @anukulSaini, can you please elaborate a bit?
like what improvements would you like to see?
how can we make the comments more helpful? where?

**Comment by anukulSaini** [comment]
hi @marsonya it would be great if you add like 2 lines after code for talking about algo and its implementation....it will save time

**Comment by anukulSaini** [comment]
There are only  code in most of the files..
