### ISSUE TITLE
Adding shuf - a way to get a random sample from a large dataset

### ISSUE THREAD

**Issue by MarkSFrancis** [TheAlgorithms/Javascript#567]
## What is shuf?
shuf is a tool to get a random sample in a random order, from a data source of an unknown size. It's used in data analytics, often as a way to get a small random sample from a data lake or warehouse, or from a large CSV file. It was originally written for `coreutils` as a CLI tool, and you can find the source for that [here](https://git.savannah.gnu.org/cgit/coreutils.git/tree/src/shuf.c).

I have reverse-engineered it to JS as an algorithm [here](https://github.com/MarkSFrancis/shuf-js)- would you be interested if I created a PR for it, to add it to this repo?

**Comment by raklaptudirm** [comment]
@MarkSFrancis I would suggest you submit a pr. The mods will check the algorithm then. Cheers!

**Comment by raklaptudirm** [comment]
@MarkSFrancis Sorry for the ping but I was wondering if you could close the issue since it has been solved.
