### ISSUE TITLE
Waiting for responses to contributions

### ISSUE THREAD

**Issue by algobytewise** [TheAlgorithms/Javascript#587]
I've tried to make several contributions to this repo in the last weeks: #575, #580, #584 & #585. Some of them have been reviewed but the pull requests are all still open without any pending requests for changes. Could someone of the members have a look at them?

**Comment by josecarlosweb** [comment]
All PRs merged. Thank you for your contributions.

**Comment by algobytewise** [comment]
Great, thank you for taking the time!
