### ISSUE TITLE
Outdated link in the wiki

### ISSUE THREAD

**Issue by vsemozhetbyt** [TheAlgorithms/Javascript#627]
[wiki](https://github.com/TheAlgorithms/Javascript/wiki) has an outdated link here:

> See our directory.

It seems the

https://github.com/TheAlgorithms/Javascript/wiki/DIRECTORY.md

should be the

https://github.com/TheAlgorithms/Javascript/blob/master/DIRECTORY.md

**Comment by raklaptudirm** [comment]
Fixed
