### ISSUE TITLE
A modification to the BinarySearchTree.js

### ISSUE THREAD

**Issue by martisss** [TheAlgorithms/Javascript#637]
Path：[Data-Structures/Tree/BinarySearchTree.js](https://github.com/TheAlgorithms/Javascript/blob/2d0da4d17dbd08a7cba3b70897417c252c0c7e12/Data-Structures/Tree/BinarySearchTree.js)

line 50 should be : `if (n.value <= this.value) {`,  otherwise you can't store duplicate numbers

**Comment by raklaptudirm** [comment]
If you want the change please open a pull request. We will review it.
