### ISSUE TITLE
Binary Search algo is missing

### ISSUE THREAD

**Issue by ritwikchakraborty123** [TheAlgorithms/Javascript#656]

**Comment by ritwikchakraborty123** [comment]
can i plz work on it

**Comment by raklaptudirm** [comment]
@ritwikchakraborty123 see https://github.com/TheAlgorithms/Javascript/blob/master/Search/BinarySearch.js
We already have binary search algorithm in our repository. If you want, you could contribute something which we still do not have. Also, there is no need for creating an issue on these matters. If you would like to contribute something, just create a pr, and we will review it.
