### ISSUE TITLE
Hi am Rik77 , to do is one my key

### ISSUE THREAD

**Issue by Rik77** [TheAlgorithms/Javascript#681]

**Comment by raklaptudirm** [comment]
Please provide more information about the issue.

**Comment by Rik77** [comment]
Хочу научиться писать колы и программы

**Comment by raklaptudirm** [comment]
Если вы хотите изучить Javascript, посмотрите [это](https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide).
