### ISSUE TITLE
There is no remove method found in BST

### ISSUE THREAD

**Issue by damla** [TheAlgorithms/Javascript#687]
## Problem

- Remove method, which is one of the fundamental methods found in Binary Search Tree, is not found in the BST implementation.

## Suggestion

- I may implement BST with ES6 and add remove function.

**Comment by raklaptudirm** [comment]
Please do the implementation and open a pr, we will review it.

**Comment by juuuuuuun** [comment]
Can I work for it? :)

**Comment by raklaptudirm** [comment]
They are already working on it. See #696.

**Comment by juuuuuuun** [comment]
> They are already working on it. See #696.

Thank you😉
