### ISSUE TITLE
Star Patterns

### ISSUE THREAD

**Issue by iamfazal** [TheAlgorithms/Javascript#743]
One of the main purposes of this repository is to learn how to solve real-time problems using different programming languages, for writing a good algorithm you must have a good grip on loops and control statements. 

creating different star patterns like triangles, diamonds, Pyramid can help you to enhances the coding skill, logic, and looping concepts

**Comment by iamfazal** [comment]
I want to contribute to this issue
Can you assign this (under 'hacktoberfest-2021' label) to me?

**Comment by raklaptudirm** [comment]
Please create a Pull request with your contribution. There is no need to create an issue.

**Comment by utsav0** [comment]
I wanna contribute to this project and I'm really interested in it But I'm new here . so, how can I contribute to this project?

**Comment by trasherdk** [comment]
@utsav0 start by reading [CONTRIBUTING](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md) :smiley:

**Comment by raklaptudirm** [comment]
See comment in #761
