### ISSUE TITLE
a new challenge alogorithm

### ISSUE THREAD

**Issue by KrishAgarwal2811** [TheAlgorithms/Javascript#765]
Exceeding words are words where the gap between two adjacent characters is increasing.
The gap is the distance in ascii

Example:

input =  update
output = False 

Explanation :
from u to p: 5
from p to d: 12
from d to a: 3
from a to t: 19
from t to e: 15

5,12,3,19,15 is not increasing.
The word "update" is not an Exceeding Word

**Comment by raklaptudirm** [comment]
@cclauss ?

**Comment by fahimfaisaal** [comment]
@raklaptudirm could I handle this solution.
