### ISSUE TITLE
Fix MinPriorityQueue implementation

### ISSUE THREAD

**Issue by lvlte** [TheAlgorithms/JavaScript#774]
[This implementation](https://github.com/TheAlgorithms/Javascript/blob/5f601fac8df00a1c0b9545436da2518a901ee859/Data-Structures/Heap/MinPriorityQueue.js) of the min-priority queue contains some inconsistencies that need to be fixed :

(I stumbled upon this while working on #720 which involves dozens of unrelated algorithms so I may have missed some things)

- `heapSort()` should be call `reverse()` and should not rely on `delete()` to reverse the heap ordering.
- `delete()` should delete the highest priority value (for now, it only decreases the heap size but the element remains in it and is just pushed back instead, like a rotation).

Also, adding some explanation (ie. why and how to use it), as well as some Jest tests would be much appreciated.

**Comment by pasagedev** [comment]
I could like work on this can assign me @raklaptudirm ?
