### ISSUE TITLE
Check given number is Triangular , Tetrahedral or Pentatope

### ISSUE THREAD

**Issue by Badhusha-Akhthaar** [TheAlgorithms/Javascript#791]
The purpose of this repository is, to check whether the given number is a triangular, tetrahedral or pentatope number or not. An additional feature will be like, if a number doesn't belong to one type, we can check what type does it fit

####  Example :  The numbers 1,3,6 belongs to Triangular.  Numbers 1,4,10 belong to tetrahedral.

[Triangular](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/First_six_triangular_numbers.svg/330px-First_six_triangular_numbers.svg.png)

[Tetrahedral](https://upload.wikimedia.org/wikipedia/commons/d/d5/Pyramid_of_35_spheres_animation.gif)

**Comment by raklaptudirm** [comment]
If you want to add the algorithm, please create a new pr.
