### ISSUE TITLE
Algorithms of design patterns

### ISSUE THREAD

**Issue by josecarlosweb** [TheAlgorithms/Javascript#792]
What about create a design pattern directory with the most popular design patterns examples?
We can create some rules like: have to be an explanation about the design pattern, the structure and one real world example.
The directory can be:
```
(folder) Design Patterns
-- (folder) Abstract Factory
-- -- AbstractFactory.js
-- -- AbstractFactoryTest.js
-- -- REAME.md
```

I can send some :)

**Comment by raklaptudirm** [comment]
@cclauss

**Comment by cclauss** [comment]
Spaces in directory names is a bad idea but other than that, I have no comment.

**Comment by cclauss** [comment]
Actually.  Design Patterns are not algorithms so I would find a different repo to land these contributions.

**Comment by raklaptudirm** [comment]
I do think we have had a conversation regarding these, and it ended something like "Design patterns are not algorithms".
