### ISSUE TITLE
An improvement on Ficbonacci function using DP

### ISSUE THREAD

**Issue by duongtq** [TheAlgorithms/Javascript#81]
// My code just improves a little
// Feel free to ask me questions

function dp_ficbo(n)
	{
		var val = [];
		for ( let i = 0; i <= n; i++)
		{
			val[i] = 0;
		}

		if ( n == 1 || n == 2)
		{
			return 1;
		}
		else
		{
			val[1] = 1;
			val[2] = 2;

			for ( let i = 3; i <= n; i++ )
			{
				val[i] = val[i - 1] + val[i - 2];
			}
		}

		return val[n - 1];
	}

console.log(dp_ficbo(20));

**Comment by ms10398** [comment]
If you feel you can make a better implementation feel free to make a PR

**Comment by duongtq** [comment]
I do not understand what PR means. If it is a sarcasm feel free not to reply.

**Comment by ms10398** [comment]
No it is not sarcasm

Sorry if you misunderstood

PR means Pull Request which means updating the code of the repo with the better approach so that I can merge it in the repository.

I have given to link for you to check just in case if you are new to GitHub 

https://help.github.com/articles/about-pull-requests/

**Comment by duongtq** [comment]
Thank you for your explanation.
I will use pull request to share the code.

**Comment by christianbender** [comment]
@duongtq This lines are needless
```js
for ( let i = 0; i <= n; i++)
{
    val[i] = 0;
}
```
Because you used dynamic arrays in javascript.

**Comment by christianbender** [comment]
@duongtq 
```js
val[1] = 1;
val[2] = 2;
```
Begin with index ```0```. Change your for-loop according to index 0

**Comment by archanaserver** [comment]
I would like to work on this by providing the solution of the Fibonacci sequence from the Brute Force Approach to the Top-Down and Bottom-Up Dynamic Approach.

**Comment by ritwikchakraborty123** [comment]
can i make a pull request...i can update the code by applying dynamic programming.

**Comment by Satzyakiz** [comment]
Is this issue still open ? I would like to work on it.

**Comment by itsvinayak** [comment]
@Satzyakiz go for it

**Comment by Satzyakiz** [comment]
Maybe something like this :
```
function fibonacci(n) {
  const fibArr = [0,1];

  for(let i=2; i<=n; i++){
    fibArr.push( fibArr[i-1] + fibArr[i-2] );
  }

  return fibArr[n-1];
}
```
This is nothing new, just avoiding the recursive calls.

**Comment by itsvinayak** [comment]
@Satzyakiz you can make a separate function for this approach and send a PR

**Comment by Satzyakiz** [comment]
Where should I keep it ? In Algorithms/Dynamic-Programming/ ?

**Comment by itsvinayak** [comment]
In same file make a function





Vinayak sharma

9259888898

IERT allahabad
CSE 3rd year

**Comment by itsvinayak** [comment]
many new algorithms are added on this topic #159
