### ISSUE TITLE
Create A utils folder for utility functions

### ISSUE THREAD

**Issue by Yatin-kathuria** [TheAlgorithms/Javascript#838]
## Hi,
I figure out that their are some algorithms which are using the same function but by creating a copy in their file. 
I find out isNumber function is used in Volume.js and In Area.js same function is created with different name validateNumericParam.
It will be good if we moved out this type of function in separate folder which contains similar kind of function.some other example are isEven , isOdd , isPositive etc

**Comment by raklaptudirm** [comment]
Any other algorithms from the repository is allowed to be imported and used.

**Comment by Yatin-kathuria** [comment]
right
