### ISSUE TITLE
Split READMEs for each folder.

### ISSUE THREAD

**Issue by co16353sidak** [TheAlgorithms/Javascript#85]
instead of keeping one solitary readme I the root folder, it would be better to add separate README to each folder.
what this would achieve would be that for someone interested in ciphers should open the folder and find details in the README specific to ciphers only.
This seems like an easy process of splitting the README into separate duplicates and then adding them to individual folders, I would really love it if I can work on this. 🥇 😃

**Comment by satishchandra538** [comment]
yes! that right by this it would be easy to understand and learn

**Comment by abhi0977** [comment]
@co16353sidak 
are you working on this?

**Comment by satishchandra538** [comment]
Sorry currently I am not working on this project.

**Comment by itsvinayak** [comment]
@abhi0977 , @satishchandra538 , @co16353sidak what about creating the wiki for this purpose

**Comment by itsvinayak** [comment]
@co16353sidak should I clean README.md
