### ISSUE TITLE
IsPowerOfTwo has bugs

### ISSUE THREAD

**Issue by Rudxain** [TheAlgorithms/Javascript#893]
JS doesn't use fixed-point int arithmetic, it uses floating-point "rationals". JS bitwise ops use "modulo" internally (specifically `mod 2 ** 32`), which removes all bits with an index greater than 31. So the bitwise int implementation doesn't work because `IsPowerOfTwo((2 ** 53 - 1) * 2 ** 32)` and `IsPowerOfTwo(Infinity)` return `true`.

I propose using trial divison by 2, since it's simple and most engines will optimize it as a simple FPFP exponent decrement. And using a "guard clause" to prevent `Infinity` or `NaN` from messing up the output:

```javascript
const IsPowerOfTwo = n =>
{
  n = n?.valueOf(); //coerce to primitive, this ensures "object-wrapped" Numbers are recognized by `isFinite` method
  //technically, negative powers of 2 are valid, but this uses a narrower definiton (only unsigneds)
  if (!Number.isFinite(n) || n < 2) return false;
  //strict equality is the same as "loose" eq, when both operands are of the same type
  while (n % 2 == 0) n /= 2;
  return n == 1
}
```

**Comment by Rudxain** [comment]
Ok, thank you for the info. I'll change the code writing style to match the standard

**Comment by raklaptudirm** [comment]
If the current implementation is working, it should be left alone. You can add your implementation as a separate function with a different name, like `isPowerOf2Iterative`. You can use the same test cases as the other algorithm to test yours.

**Comment by Rudxain** [comment]
I think it's better to leave it as it is. Since it is in the "bit manipulation" it implicitly states that all inputs must be valid 32bit ints, so `Infinity` is not a valid input, which means it's okay for the return value to be wrong.
I'll close the issue, thank you for your time and help
