### ISSUE TITLE
Anagram is or not case sensitive!

### ISSUE THREAD

**Issue by fahimfaisaal** [TheAlgorithms/Javascript#901]
From my research, I've come to know anagram is not case sensitive, but this [checkAnagram](https://github.com/TheAlgorithms/Javascript/blob/master/String/CheckAnagram.js) function is case-sensitive. it's can't pass this test case **“Eleven plus two” is an anagram of “Twelve plus one”**

**Comment by raklaptudirm** [comment]
Please open a pull request to fix this issue.

**Comment by fahimfaisaal** [comment]
Ok
