### ISSUE TITLE
Fix the SquareRoot.js function inside Math folder

### ISSUE THREAD

**Issue by Ankush263** [TheAlgorithms/Javascript#924]
I am going to write a Test case of SquareRoot function, but it appears it gives the sqrt(144) = 13.7802299905638
It's not closed to 12.

**Comment by raklaptudirm** [comment]
Try increasing the precision, that should work:
```js
sqrt(144, 10) // gives 12
```

**Comment by Ankush263** [comment]
Yes, it works perfectly.....Now I can add some test cases to it. Thank You
