### ISSUE TITLE
Got issue on standard config. Should add `@babel/eslint-parser`

### ISSUE THREAD

**Issue by fahimfaisaal** [TheAlgorithms/Javascript#930]
There an issue on using [PrivateClassFeatures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) in standard js, cause it's can't recognize the `#` private symbol and throw to me this error: 
```bash
$ yarn standard --fix
yarn run v1.22.17
$ C:\Users\Maxell\Desktop\Javascript\node_modules\.bin\standard --fix
standard: Use JavaScript Standard Style (https://standardjs.com)
  C:\Users\Maxell\Desktop\Javascript\Cache\LFUCache.js:27:5: Parsing error: Unexpected character '#'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

From standard [doc](https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features) we should use the `@babel/eslint-parser` plugin to fix it.

**Comment by raklaptudirm** [comment]
Open a pull request to fix the issue.
