### ISSUE TITLE
In Queue the `dequeue` should be O(1) complexity

### ISSUE THREAD

**Issue by fahimfaisaal** [TheAlgorithms/JavaScript#942]
From this [Queue](https://github.com/TheAlgorithms/Javascript/blob/ad68c639476804a27342e3416d060cec1f5037ba/Data-Structures/Queue/Queue.js#L28) implementation I believe the Operation is **O(n)** cause the  complexity of  `Array.prototype.shift` methods is **O(n)**, [see](https://stackoverflow.com/questions/22614237/javascript-runtime-complexity-of-array-functions)

**Comment by ayDavidGitHere** [comment]
Dequeue on queue works on a O(n) complexity.
To achieve dequeue on O(n) use linked-lists.

https://github.com/ayDavidGitHere/Javascript/tree/master/Data-Structures/Linked-List

**Comment by fahimfaisaal** [comment]
Yeah, I see.

**Comment by appgurueu** [comment]
The queue should be implemented using linked lists. The current implementation is clearly suboptimal for no good reason.

**Comment by raklaptudirm** [comment]
@fahimfaisaal Are you working on this issue?

**Comment by fahimfaisaal** [comment]
Yep.. I'll send pr soon.

**Comment by raklaptudirm** [comment]
@fahimfaisaal Are you working on this, or should I put this issue up for grabs?

**Comment by fahimfaisaal** [comment]
@raklaptudirm I apologize for my latency.

**Comment by raklaptudirm** [comment]
#1005 fixes this.
