### ISSUE TITLE
As a beginner, what can I contribute?

### ISSUE THREAD

**Issue by utsav0** [TheAlgorithms/Javascript#949]
I'm a beginner in open source but I really love to use algorithms. So, how I can contribute here? Like, can I improve any random thing and then raise a pull request or there is a specific processor for it?

**Comment by raklaptudirm** [comment]
Yes, you can improve any of the existing algorithms and/or add your own. To do this, just open a new pull request and we will review it. Before contributing, read the [`CONTRIBUTING.md`](https://github.com/TheAlgorithms/Javascript/blob/master/CONTRIBUTING.md) file, as it guides how to contribute to this repository
