### ISSUE TITLE
Typo: Javascript > JavaScript

### ISSUE THREAD

**Issue by gpresland** [TheAlgorithms/JavaScript#966]
The repository name and _about_ are missing capitalization of the _S_ in JavaScript.

The _about_ reads:

```diff
-Algorithms implemented in Javascript for beginners, following best practices.
+Algorithms implemented in JavaScript for beginners, following best practices.
```

**Comment by appgurueu** [comment]
Agreed, but renaming the repo might be somewhat problematic. A pretty minor issue.

**Comment by raklaptudirm** [comment]
@appgurueu From the GitHub docs:
> In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location.

**Comment by Panquesito7** [comment]
Renamed the description for now. 🙂

**Comment by appgurueu** [comment]
> @appgurueu From the GitHub docs:
> 
> > In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location.

I'm aware. This will print a nasty warning though.

**Comment by raklaptudirm** [comment]
@appgurueu, that can act as a notification to change whatever link they are using.

**Comment by appgurueu** [comment]
After more thought, the redirect is most likely fine (especially as this repo doesn't use GH pages).

**Comment by raklaptudirm** [comment]
@AnupKumarPanwar up

**Comment by poyea** [comment]
I agree with this, and redirect should work fine for GitHub links, as long as there's no `Javascript` repo is created in the future. cc. @AnupKumarPanwar, @dynamitechetan, @jainkuniya, @nikhilkala, @r0hit-gupta

**Comment by raklaptudirm** [comment]
This issue has been resolved.
