### ISSUE TITLE
wiggle sort seems incorrect

### ISSUE THREAD

**Issue by BranAndSceolan** [TheAlgorithms/Javascript#988]
Hello!
From the comments on the wiggle sort code I got that it is intended to sort an array arr like this:
a[0] <= a[1] >= a[2] <= a[3] >= a[4] <=...

I tested the code using an array [3, 5, 6, 1].
I got [3, 6, 5, 1], which is not fulfilling the condition stated above. 

There are possible solutions for this case, for example [3, 5, 1, 6].

If this is an error I would like to try and fix it. If it is not, please reply, so I might learn what I misinterpreted.

**Comment by appgurueu** [comment]
You're right, this is a bug. Feel free to fix it.

**Comment by raklaptudirm** [comment]
@BranAndSceolan Inform here if you want to work on it and we will assign you.

**Comment by BranAndSceolan** [comment]
I am already planing to write a wriggle sort in java, therefore I would be happy to be assigned to this issue.
