### ISSUE TITLE
Typescript version?

### ISSUE THREAD

**Issue by alterstep** [TheAlgorithms/Javascript#99]
These algorithm implementations are very helpful. But they could be shorter and easier to understand with Typescript, using Typescript features. Many people use Typescript instead of directly Javascript now. How about converting these algorithms to Typescript?

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Javascript/search?l=typescript

**Comment by itsvinayak** [comment]
@cclauss  should we close this issue
